# todo: populate these dynamically
- name: append etc hosts file
  blockinfile:
    path: /etc/hosts
    content: |
      10.138.96.16   fed-master
      10.138.234.214   fed-node

- name: append kubernetes master in config file
  lineinfile:
    path: /etc/kubernetes/config
    regexp: KUBE_MASTER.*
    line: 'KUBE_MASTER="--master=http://fed-master:8080"'

- name: apply  master configs
  block:
    - name: api server configurations
      lineinfile:
        path: /etc/kubernetes/apiserver
        regexp: KUBE_API_ADDRESS.*
        line: 'KUBE_API_ADDRESS="--address=0.0.0.0"'

    - name: etcd listening configs
      lineinfile:
        path: /etc/etcd/etcd.conf
        regexp: ETCD_LISTEN_CLIENT_URLS.*
        line: 'ETCD_LISTEN_CLIENT_URLS="http://0.0.0.0:2379"'
    
    - name: enable services
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - etcd 
        - kube-apiserver 
        - kube-controller-manager 
        - kube-scheduler
      register: master_change
  when: kube_caste in ['fed-master']

- name: apply node configs
  block:
    - name: kubelet configuration
      lineinfile:
        path: /etc/kubernetes/kubelet
        regexp: KUBELET_ADDRESS.*
        line: KUBELET_ADDRESS="--address=0.0.0.0"

    - name: kubelet configuration
      lineinfile:
        path: /etc/kubernetes/kubelet
        regexp: KUBELET_HOSTNAME.*
        line: KUBELET_HOSTNAME="--hostname-override=fed-node"

    - name: kubelet configuration
      lineinfile:
        path: /etc/kubernetes/kubelet
        regexp: KUBELET_ARGS.*
        line: KUBELET_ARGS="--cgroup-driver=systemd --kubeconfig=/etc/kubernetes/master-kubeconfig.yaml

    - name: kubeconfig template
      template:
        src: kubeconfig.j2
        dest: /etc/kubernetes/master-kubeconfig.yaml

    - name: enable services
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - kube-proxy
        - kubelet
        - docker
      register: node_change
  when: kube_caste in ['fed-node']



