# todo: populate these dynamically
- name: append etc hosts file
  blockinfile:
    path: /etc/hosts
    content: |
      138.68.20.208   fed-master
      157.230.154.247   fed-node

- name: append kubernetes master in config file
  lineinfile:
    path: /etc/kubernetes/config
    regexp: KUBE_MASTER.*
    line: 'KUBE_MASTER="--master=http://fed-master:8080"'

